### ISSUE TITLE
Minor/Major issues around the LOTD mueseum in solitude

### ISSUE THREAD

**Issue by micmou** [SudoDoubleDog/Essentia#4]
First issue is in the courtyard outside the mueseum there is a stone wall that is not suppose to be there and can be seen through and has weird collision.

https://imgur.com/a/8Eyo7rz

The next issue is with the buttons that unlock ice cream assassins spoon inside the museum once pressed they continually act like they are being pressed making a horrendous racket that never ends.

https://imgur.com/a/DV3DVI9

I am on 1.1.1 and I have not added anything to the list and have it configured as you intend.

**Comment by micmou** [comment]
I am liking this one a lot Shelb I plan on playing it a lot more and ill leave whatever issues I find for you. I was a huge fan of NOISE and this fills that spot in my heart really well.

**Comment by micmou** [comment]
The issue with the buttons has been pinpointed already by the LOTD team upon reading there FAQ they have this to say.

Buttons or raised stones in the museum once pressed trigger over and over in a loop
You have a mod conflict and it is probably Brutal Flora Harvest Fix.  Switch to Wiseman303's Flora Fixes - Revamped or another mod that contains the fix, such as Complete Crafting and Alchemy Overhaul.

**Comment by SudoDoubleDog** [comment]
How did you find this repo

**Comment by SudoDoubleDog** [comment]
The issues you reported are known issues with the museum since v5, I'm closing this since nothing in my list conflicts with LOTD.
